git add dateutil
git add procname
git add pycassa
git add pymongo
git add Pyro
git add pytz
git add redis
git add rq
git add thrift
git add times
git add ZODB3
git add cli_adm.py
git add conf.py
git add exampleapp.py
git add friends13C321_d.py
git add grad.py
git add mdFuzzy.so
git add migr12.py
git add mongo.py
git add Procfile
git add umisc.py
git add utils.py
git add worker.py
git add *.pyc
git add *.py